global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "haproxy"
    metrics_path: /metrics
    static_configs:
      - targets: ["haproxy:8404"]

  - job_name: "openai-endpoint"
    metrics_path: /metrics
    static_configs:
      - targets: ["openai-endpoint:30000"]

  - job_name: "nvidia_gpu_exporter"
    static_configs:
      - targets: ["exporter:9400"]
